### PR TITLE
Centralize FusionInterrupt handling in embedding layer

### LINKED ISSUE #517: Isolate interrupt handling for the embedding layer
## Technical context

`Evaluator` provides thread-local context for Fusion evaluation, including access to `GlobalState` shared across the entire `FusionRuntime`.  As a result, it is a required argument, directly or indirectly, to almost everything that happens in the language and applications embedding it.

From the perspective of the embedding APIs, particularly `TopLevel`, transitions into and out of the `Evaluator` require special care across a few dimensions, most notably value projection (converting between Java and Fusion representations) and exception handling.

One specific exception requires explicit treatment at the embedding layer: `FusionInterrupt`.  This is an internal unchecked exception type [thrown by the interpreter loop](https://github.com/ion-fusion/fusion-java/blob/83d7b9f567543fc29486c7163445b9d7d71ef21f/runtime/src/main/java/dev/ionfusion/fusion/Evaluator.java#L532-L535) when it detects a `Thread.interrupt()` condition.  Modulo potential changes due to issues #479 and #132 this must be caught and replaced by the checked form `FusionInterruptedException`, which extends `FusionException`.  This is intended to allow applications to handle interrupts.  (I am not advocating for this design here!  It's debatable.) 

## What should change

This interrupt exception handling is boilerplate repeated everywhere the `Evaluator` is invoked from the `embed` layer.  Or at least it should be!  But it's not; see `StandardTopLevel`:

```
    public IonValue ionize(Object fusionValue, ValueFactory factory)
        throws FusionException
    {
        return FusionValue.copyToIonValue(myTopLevel.getEvaluator(), fusionValue, factory);
    }
```

What I'd like to accomplish in this issue is to DRY the exception handling so its easier to do properly, and harder (if not impossible) to forget.  I bet this involves some use of a functional interface to be invoked within the idiomatic try/catch that's currently boilerplate.  Lambdas and method interfaces didn't exist in Java 7 when this code was written!

The goal is to have that exception handling in exactly one place.  Beyond making the embedding code more robust, it will make it easier to alter Fusion's exception protocol in the future, if needed.

### PR DESCRIPTION
**Pull request by DimitriosDalaklidhs**
Closes #517

Introduces `EvalTask<T>` functional interface and `withEvaluator()` helper
on `StandardTopLevel` to centralize `FusionInterrupt → FusionInterruptedException`
translation in one place.

All call sites in `StandardTopLevel` and `StandardRuntime` now use
`withEvaluator()`, including the previously missing `ionize` and
`ionizeMaybe` methods in `StandardRuntime`.

### CODE REVIEW

File: runtime/src/main/java/dev/ionfusion/fusion/StandardRuntime.java [hunk 1]
```diff
@@ -37,8 +37,8 @@ final class StandardRuntime
     {
         IonSystem ionSystem =
             IonSystemBuilder.standard()
-                .withCatalog(builder.getDefaultIonCatalog())
-                .build();
+                            .withCatalog(builder.getDefaultIonCatalog())
```
Comment (SharkBaitDLS) [inline runtime/src/main/java/dev/ionfusion/fusion/StandardRuntime.java:40]: Doesn't necessarily need to be in scope for this PR, but we must have some missing settings in our `.editorconfig` if IDEs are disagreeing on our continuation indent.

File: runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java [hunk 2]
```diff
@@ -77,6 +77,28 @@ ModuleRegistry getRegistry()
         return myNamespace.getRegistry();
     }
 
+    @FunctionalInterface
+    interface EvalTask<T>
+    {
+        T run() throws FusionException;
+    }
+
+    <T> T withEvaluator(EvalTask<T> task)
```
Comment (SharkBaitDLS) [inline runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java:86]: The concept of this functional interface is I think absolutely the right abstraction, but I'm struggling a bit with the naming given that an `Evaluator` isn't actually part of the contract. To me `runInterruptible` or something similar captures the intention more clearly. I'm curious why this name was chosen, perhaps there's a future intention here that I'm not following?

Comment (DimitriosDalaklidhs) [reply runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java:86]: The intention was that the method wraps operations that need to run within the evaluator because the issue was" transitions into and out of the Evaluator require special care", hence withEvaluator. It's the same pattern as withConnection, withTransaction, withLock in Java. The evaluator is the resource being scoped. However, the method doesn't actually pass the evaluator to the callable, and the evaluator isn't in the interface contract. So the name implies something it doesn't rreally deliver(oops). runInterruptible is more honest about what it actually does that is translating FusionInterrupt to FusionInterruptedExcept. I think I will wait for Todd's opinion on this.

Comment (DimitriosDalaklidhs) [reply runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java:86]: @toddjonker

**Comment by toddjonker** [comment]
@DimitriosDalaklidhs Can you please do a (non-merge) rebase and force-push a single commit with the relevant change?  This is currently on a lengthy fork of the upstream mainline.  The main impact is that when I merge the change I have to filter through all the previously-applied and intermediate commit logs.

File: runtime/src/main/java/dev/ionfusion/fusion/StandardRuntime.java (hunk 1 above)
Comment (toddjonker) [reply runtime/src/main/java/dev/ionfusion/fusion/StandardRuntime.java:40]: To be fair, almost all of the editorconfig settings are IntelliJ-specific.

But in this case the change is actually correct WRT to the settings and my preferred style for method chaining.

File: runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java [hunk 3]
```diff
@@ -77,6 +77,28 @@ ModuleRegistry getRegistry()
         return myNamespace.getRegistry();
     }
 
+    @FunctionalInterface
+    interface EvalTask<T>
+    {
+        T run() throws FusionException;
```
Comment (toddjonker) [inline runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java]: Did you consider having this take the `Evaluator`?  That would help ensure that the evaluator used to run the task is the same one used to perform any pre- or post-processing around the task.

In particular, I have thought about allowing the app to customize how Fusion exceptions are surfaced through the TopLevel.  Maybe they want to use custom ones, or do something else entirely.  And that would ideally be parameterized locally.

This would also help limit the uses of `myEvaluator`, which leaves a clean way to do things like inject parameters before evaluation; see #98

File: runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java (hunk 2 above)
Comment (toddjonker) [reply runtime/src/main/java/dev/ionfusion/fusion/StandardTopLevel.java:86]: I'd go for something more general than just "interruptible", since I expect we'll extend this to do more extensive exception transformation.  In fact, I have considered transforming _all_ raised values at this layer.   Meaning: we'll have one internal exception type that wraps the Fusion-side raised value; in most cases that value will be a Fusion [record instance](https://github.com/ion-fusion/fusion-java/blob/9fdf41f955fc428b5e1b045ca4151157a02882b4/runtime/src/main/java/dev/ionfusion/fusion/Records.java#L106) of type `exn` (or subtype), and then here we'll detect that and transform some of them to similarly-typed Java exceptions.

I noted in a review comment that I think this interface should take the `Evaluator` as an argument.  That leads me to suggest interface `EvaluatorTask<T>` and method `runTask(EvaluatorTask)` or even just `evaluate(EvaluatorTask)`.

We don't need to over-analyze this, it's isolated to one file.

**Review by toddjonker — APPROVED** [review]
I made some small formatting changes, and this is good to go.

**Comment by toddjonker** [comment]
Oh weird, looks like GitHub is requiring a non-me reviewer since I committed a change to the PR.  So this is back at you @SharkBaitDLS

**Review by SharkBaitDLS — APPROVED** [review]
